import type { Metadata } from "next";
import "@/public/styles/globals.css";
import { charisSIL, inter } from "@/shared/fonts";
import { cn } from "@/shared/utils/cn";
import { NextIntlClientProvider } from "next-intl";
import { Navbar } from "@/widgets/common/Navbar";
import { Footer } from "@/widgets/common/Footer";

export const metadata: Metadata = {
  title: "Latin Russian Corpus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextIntlClientProvider>
        <body className={cn("antialiased", charisSIL.variable, inter.variable)}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
