import type { Metadata } from "next";
import "@/public/styles/globals.scss";
import { charisSIL, inter } from "@/shared/fonts";
import { cn } from "@/shared/utils/cn";

export const metadata: Metadata = {
  title: "Latin Russian Corpus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", charisSIL.variable, inter.variable)}>{children}</body>
    </html>
  );
}
